Server:
  Host: localhost
  Port: 4000
  Debug: false
  TLS: true
  Certificate: certificate.crt
  PrivateKey: private.key

Session:
  Store: cookie  
  Secret: 6251655468576D5A
  MaxAge: 1800
  HttpOnly: true
  Secure: false

Redis:
  Host: localhost
  Port: 6379
  Password: pUrWtZw3y6B8DaGdJfMjQmSpVsXu2x4z6C9EbGeKgNkRnTqWtY
  Protocol: tcp
  Connections: 10

OIDC:
  Provider: https://sso-int.daimler.com
  ClientId: 7ece1151-b0fd-4143-bcbc-ba8b19836cd7
  ClientSecret: ffeb07d5-b5eb-42f8-8830-b34dc2769dcb
  RedirectURL: https://localhost:4200/login
  Scopes:
  - openid


