Server:
  Host: localhost
  Port: 4200  
  Debug: false
  TLS: true
  Certificate: certificate.crt
  PrivateKey: private.key

Session:
  Store: cookie  
  Secret: 6251655468576D5A

Redis:
  Host: localhost
  Port: 6379
  Password: pUrWtZw3y6B8DaGdJfMjQmSpVsXu2x4z6C9EbGeKgNkRnTqWtY
  Protocol: tcp
  Connections: 10

OIDC:
  Provider: 
  ClientId: 
  ClientSecret: 
  RedirectURL: https://localhost:4200/login
  Scopes:
    - openid

CORS:
  AllowOrigins:
    - https://localhost:4200
  AllowMethods:
    - GET
    - PATCH
    - HEAD
    - OPTIONS
  AllowHeaders:
    - Origin
    - Content-Length
    - Content-Type
  ExposeHeaders:
    - Content-Length
    - Content-Type
  AllowCredentials: true
  MaxAge: 86400
  



